version: "2.4"

x-healtcheck:
  &service-healtcheck
  test: ["CMD-SHELL", 'echo -ne "GET /actuator/health HTTP/1.0\n\n" | nc localhost ${PORT:-9000} | grep "{\"status\":\"UP\"}"']
  interval: 30s
  timeout: 5s
  retries: 3
  start_period: 300s

services:
  did-resolver:
    image: nexus.iroha.tech:19001/sora-middleware/didresolver:${VERSION:-latest}
    expose:
      - 9000
    labels:
      - "traefik.docker.network=traefik-net"
      - "traefik.enable=true"
      - "traefik.backend.healthcheck.port=9000"
      - "traefik.backend.healthcheck.path=/actuator/health"
      - "traefik.frontend.rule=Host:${DIDRESOLVER_HOST:?DIDRESOLVER_HOST is not defined}"
      - "traefik.port=9000"
      - filebeat.module=docker
      - filebeat.fields.app=did-resolver
      - filebeat.fields.project=sora
      - filebeat.fields.env=${ENVIRONMENT:?ENVIRONMENT is not defined}
      - filebeat.fields.logtype=sora-java-log
      - filebeat.multiline.pattern='^\d{4}-\d{2}-\d{2}'
      - filebeat.multiline.negate=true
      - filebeat.multiline.match=after
    mem_limit: 512m
    environment:
      - "SPRING_PROFILES_ACTIVE=cloud"
      - "SPRING_CLOUD_VAULT_ENABLED=false"
      - "SPRING_CLOUD_CONSUL_HOST=consul"
      - "SPRING_CLOUD_CONSUL_PORT=8500"
      - "SPRING_CLOUD_CONSUL_CONFIG_ACL_TOKEN=${CONSUL_ACL_TOKEN:?CONSUL_ACL_TOKEN is not defined}"
      - "SPRING_CLOUD_CONSUL_CONFIG_PREFIX=sora"
      - "SPRING_CLOUD_CONSUL_CONFIG_NAME=did-resolver"
      - "SPRING_CLOUD_CONSUL_DISCOVERY_ENABLE=false"
      - "SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER=false"
    networks:
      - sora-net
      - traefik-net
      - consul-net
    healthcheck: *service-healtcheck
    restart: on-failure

networks:
  sora-net:
    external:
      name: sora-net
  traefik-net:
    external:
      name: traefik-net
  consul-net:
    external:
      name: consul-net
